project_id = "mfbvobfuoeplmcykfxwo"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.verify-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.expire-trials]
verify_jwt = false
